openapi: 3.0.3
info:
  description: "The GL.iNet API is organized around REST. Our API has predictable\
    \ resource-oriented URLs, accepts form-encoded request bodies, and returns JSON-encoded\
    \ responses."
  title: GL.iNet API
  version: 3.0.1
externalDocs:
  url: https://dev.gl-inet.com/api/
servers:
- url: https://192.168.8.1
tags:
- name: router
paths:
  /router/login:
    post:
      operationId: routerLogin
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RouterLogin'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RouterLogin'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RouterLoginResponse'
          description: Success
      summary: Log in to the router. No login permission required.
      tags:
      - router
  /router/hello:
    get:
      operationId: getRouterHello
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RouterHello'
          description: Success
      summary: Check router is connected and configured. No login permission required.
      tags:
      - router
components:
  schemas:
    RouterHello:
      example:
        code: 0
      properties:
        code:
          type: integer
      type: object
    RouterLogin:
      example:
        pwd: pwd
      properties:
        pwd:
          type: string
      type: object
    RouterLoginResponse:
      example:
        code: 0.8008281904610115
        token: token
      properties:
        code:
          description: "Code:\n  * `0` success\n  * `-1` invalid user, permission\
            \ denied or not logged in\n  * `-4` invalid parameter, value or format\n\
            \  * `-5` no parameter found\n  * `-6` time out\n  * `-9` wrong password\n"
          enum:
          - 0
          - -1
          - -4
          - -5
          - -6
          - -9
          type: number
        token:
          type: string
      type: object
  securitySchemes:
    token:
      in: header
      name: Authorization
      type: apiKey
